# This file was generated by Nuitka

# Stubs included by default
import os

def get_store_path(filename: str) -> typing.Any:
    ...

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os