# This file was generated by liblab | https://liblab.com/

from enum import Enum


class AssetErrorType(Enum):
    """An enumeration representing different categories.

    :cvar FETCHHTTPERROR: "fetch_http_error"
    :vartype FETCHHTTPERROR: str
    :cvar INVALIDUPLOAD: "invalid_upload"
    :vartype INVALIDUPLOAD: str
    :cvar EXPIREDUPLOAD: "expired_upload"
    :vartype EXPIREDUPLOAD: str
    :cvar INVALIDAUDIOLANGCODE: "invalid_audio_lang_code"
    :vartype INVALIDAUDIOLANGCODE: str
    :cvar CANTDETECTAUDIOLANGUAGE: "cant_detect_audio_language"
    :vartype CANTDETECTAUDIOLANGUAGE: str
    """

    FETCHHTTPERROR = "fetch_http_error"
    INVALIDUPLOAD = "invalid_upload"
    EXPIREDUPLOAD = "expired_upload"
    INVALIDAUDIOLANGCODE = "invalid_audio_lang_code"
    CANTDETECTAUDIOLANGUAGE = "cant_detect_audio_language"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, AssetErrorType._member_map_.values()))
