# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .audio_track import AudioTrack


@JsonMap({})
class AudioTrackList(BaseModel):
    """AudioTrackList

    :param rows: rows
    :type rows: List[AudioTrack]
    """

    def __init__(self, rows: List[AudioTrack]):
        """AudioTrackList

        :param rows: rows
        :type rows: List[AudioTrack]
        """
        self.rows = self._define_list(rows, AudioTrack)
