# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class AudioTrackCreate(BaseModel):
    """AudioTrackCreate

    :param file: File to upload. Maximum filesize is 100.0 MB.
    :type file: bytes
    :param lang_code: Language code of the object. Language must be valid BCP 47.
    :type lang_code: str
    :param title: Title of the audio track.
    :type title: str
    """

    def __init__(self, file: bytes, lang_code: str, title: str):
        """AudioTrackCreate

        :param file: File to upload. Maximum filesize is 100.0 MB.
        :type file: bytes
        :param lang_code: Language code of the object. Language must be valid BCP 47.
        :type lang_code: str
        :param title: Title of the audio track.
        :type title: str
        """
        self.file = file
        self.lang_code = lang_code
        self.title = self._define_str("title", title, max_length=64)
