# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({"e_tag": "ETag", "part_number": "PartNumber"})
class DirectUploadPart(BaseModel):
    """DirectUploadPart

    :param e_tag: `etag` of the part returned after uploading it.
    :type e_tag: str
    :param part_number: The number of the part.
    :type part_number: int
    """

    def __init__(self, e_tag: str, part_number: int):
        """DirectUploadPart

        :param e_tag: `etag` of the part returned after uploading it.
        :type e_tag: str
        :param part_number: The number of the part.
        :type part_number: int
        """
        self.e_tag = self._define_str("e_tag", e_tag, min_length=1)
        self.part_number = part_number
