# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .upload_metadata import UploadMetadata


@JsonMap({})
class DirectUploadStart(BaseModel):
    """Schema used to start a multipart direct upload to our S3 storage.

    :param filename: Filename of the file.Filename must have a non-empty extension.
    :type filename: str
    :param metadata: The nested schema to upload a video.
    :type metadata: UploadMetadata
    """

    def __init__(self, filename: str, metadata: UploadMetadata):
        """Schema used to start a multipart direct upload to our S3 storage.

        :param filename: Filename of the file.Filename must have a non-empty extension.
        :type filename: str
        :param metadata: The nested schema to upload a video.
        :type metadata: UploadMetadata
        """
        self.filename = filename
        self.metadata = self._define_object(metadata, UploadMetadata)
