# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class PartIdResponse(BaseModel):
    """PartIdResponse

    :param url: Pre-signed url to directly upload the part.
    :type url: str
    """

    def __init__(self, url: str):
        """PartIdResponse

        :param url: Pre-signed url to directly upload the part.
        :type url: str
        """
        self.url = url
