"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from orq_poc_python_multi_env_version.types import BaseModel
from typing import List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


ValueTypedDict = TypeAliasType("ValueTypedDict", Union[str, List[str]])
r"""The feedback value. For single selection of multiple choice, the value should be an array of strings. For `correction`, the value should be a string."""


Value = TypeAliasType("Value", Union[str, List[str]])
r"""The feedback value. For single selection of multiple choice, the value should be an array of strings. For `correction`, the value should be a string."""


class CreateFeedbackRequestBodyTypedDict(TypedDict):
    r"""Feedback submission payload"""

    value: ValueTypedDict
    r"""The feedback value. For single selection of multiple choice, the value should be an array of strings. For `correction`, the value should be a string."""
    trace_id: str
    r"""The id returned by the [`get_config`]() or [`invoke`](https://docs.orq.ai/reference/post_deployments-invoke-1) endpoints"""
    property2: NotRequired[str]
    r"""A string describing the specific property or aspect rated."""


class CreateFeedbackRequestBody(BaseModel):
    r"""Feedback submission payload"""

    value: Value
    r"""The feedback value. For single selection of multiple choice, the value should be an array of strings. For `correction`, the value should be a string."""

    trace_id: str
    r"""The id returned by the [`get_config`]() or [`invoke`](https://docs.orq.ai/reference/post_deployments-invoke-1) endpoints"""

    property2: Optional[str] = None
    r"""A string describing the specific property or aspect rated."""


CreateFeedbackValueTypedDict = TypeAliasType(
    "CreateFeedbackValueTypedDict", Union[str, List[str]]
)
r"""The feedback value. For single selection of multiple choice, the value should be an array of strings. For `correction`, the value should be a string."""


CreateFeedbackValue = TypeAliasType("CreateFeedbackValue", Union[str, List[str]])
r"""The feedback value. For single selection of multiple choice, the value should be an array of strings. For `correction`, the value should be a string."""


class CreateFeedbackResponseBodyTypedDict(TypedDict):
    r"""Successful operation"""

    value: CreateFeedbackValueTypedDict
    r"""The feedback value. For single selection of multiple choice, the value should be an array of strings. For `correction`, the value should be a string."""
    trace_id: str
    r"""The id returned by the [`get_config`]() or [`invoke`](https://docs.orq.ai/reference/post_deployments-invoke-1) endpoints"""
    id: str
    property2: NotRequired[str]
    r"""A string describing the specific property or aspect rated."""


class CreateFeedbackResponseBody(BaseModel):
    r"""Successful operation"""

    value: CreateFeedbackValue
    r"""The feedback value. For single selection of multiple choice, the value should be an array of strings. For `correction`, the value should be a string."""

    trace_id: str
    r"""The id returned by the [`get_config`]() or [`invoke`](https://docs.orq.ai/reference/post_deployments-invoke-1) endpoints"""

    id: str

    property2: Optional[str] = None
    r"""A string describing the specific property or aspect rated."""
