
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-28T16:01:35+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "14598a23d926875553ef9493814b0218d64573ae",
 "version": "0.4.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
