
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-26T15:03:17+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7dc2c10ed6e108b72b5ec2f1eae7ceb846bafca1",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
