DOMAIN = "meteocat"
DEFAULT_NAME = "Meteocat"
BASE_URL = "https://api.meteo.cat"
MUNICIPIS_LIST_URL = "/referencia/v1/municipis"
MUNICIPIS_HORA_URL = "/pronostic/v1/municipalHoraria/{codi}"
MUNICIPIS_DIA_URL = "/pronostic/v1/municipal/{codi}"