"""
    EMIL BillingService

    The EMIL BillingService API description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: kontakt@emil.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eis.billing
from eis.billing.model.policy_billing_date_class import PolicyBillingDateClass
globals()['PolicyBillingDateClass'] = PolicyBillingDateClass
from eis.billing.model.list_policies_billing_dates_response_class import ListPoliciesBillingDatesResponseClass


class TestListPoliciesBillingDatesResponseClass(unittest.TestCase):
    """ListPoliciesBillingDatesResponseClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListPoliciesBillingDatesResponseClass(self):
        """Test ListPoliciesBillingDatesResponseClass"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListPoliciesBillingDatesResponseClass()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
