
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-27T15:40:54-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "89a1c8b787689c5ad45bd6035d48170832bc8196",
 "version": "2024.11.27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
