
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-26T15:40:34-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "0df563e61fe8eb163918e944da75e84ccd5c07d4",
 "version": "v0.0.39"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
