
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-27T15:28:36+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b9534cec6a600948304fb8bb62eba25195a2a74",
 "version": "1.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
