# Generated by Django 4.2.11 on 2024-05-06 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("djangoldp_energiepartagee", "0105_alter_capitaldistribution_actor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capitaldistribution",
            name="actor",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capital_distribution",
                to="djangoldp_energiepartagee.actor",
                verbose_name="Acteur",
            ),
        ),
    ]
