
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-28T15:48:58+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e33d9eb686e407de0e785f63447eb9f9f492ba5b",
 "version": "0.4.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
