from _typeshed import Incomplete

class Cache:
    cache_dir: Incomplete
    manifest_path: Incomplete
    checkpoint_order: Incomplete
    def __init__(self, cache_dir: str = 'pipeline_cache') -> None: ...
    def checkpoint(self, name: Incomplete | None = None, exclude_args: Incomplete | None = None): ...
    def truncate_cache(self, starting_from_checkpoint_name) -> None: ...
    def clear_cache(self) -> None: ...
    def list_checkpoints(self): ...
