
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-27T11:02:14+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "26cb13d000c17f7504dc6ce1147ec73317a1034f",
 "version": "2.0.0a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
