
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-25T17:14:59-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "6cb3bc2b32021a12d843509bfc0d0de3dac6b369",
 "version": "2.50.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
