# coding: utf-8

"""
    Orbit Determination API

    Orbit Determination API

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MeasurementType(str, Enum):
    """
    MeasurementType
    """

    """
    allowed enum values
    """
    GPS_NMEA = 'GPS_NMEA'
    POSITION = 'POSITION'
    POSITION_VELOCITY = 'POSITION_VELOCITY'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MeasurementType from a JSON string"""
        return cls(json.loads(json_str))


