# coding: utf-8

"""
    Orbit Determination API

    Orbit Determination API

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OrbitalProcessNoiseProviderType(str, Enum):
    """
    Type of state noise models that can be used during orbit determination with sequential filters
    """

    """
    allowed enum values
    """
    CONSTANT = 'CONSTANT'
    STATE_NOISE_COMPENSATION = 'STATE_NOISE_COMPENSATION'
    TIME_LINEAR = 'TIME_LINEAR'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OrbitalProcessNoiseProviderType from a JSON string"""
        return cls(json.loads(json_str))


