# This file was generated by liblab | https://liblab.com/

from enum import Enum


class AudioTrackType(Enum):
    """An enumeration representing different categories.

    :cvar EMBEDDED: "embedded"
    :vartype EMBEDDED: str
    :cvar ALTERNATE: "alternate"
    :vartype ALTERNATE: str
    """

    EMBEDDED = "embedded"
    ALTERNATE = "alternate"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, AudioTrackType._member_map_.values()))
