# This file was generated by liblab | https://liblab.com/

from enum import Enum


class AudioTrackStatus(Enum):
    """An enumeration representing different categories.

    :cvar QUEUED: "queued"
    :vartype QUEUED: str
    :cvar READY: "ready"
    :vartype READY: str
    :cvar ERRORED: "errored"
    :vartype ERRORED: str
    """

    QUEUED = "queued"
    READY = "ready"
    ERRORED = "errored"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, AudioTrackStatus._member_map_.values()))
