# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .engagement_stats_row import EngagementStatsRow


@JsonMap({})
class EngagementStats(BaseModel):
    """EngagementStats

    :param rows: rows
    :type rows: List[EngagementStatsRow]
    """

    def __init__(self, rows: List[EngagementStatsRow]):
        """EngagementStats

        :param rows: rows
        :type rows: List[EngagementStatsRow]
        """
        self.rows = self._define_list(rows, EngagementStatsRow)
