# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .project import Project


@JsonMap({})
class ProjectList(BaseModel):
    """ProjectList

    :param rows: rows
    :type rows: List[Project]
    """

    def __init__(self, rows: List[Project]):
        """ProjectList

        :param rows: rows
        :type rows: List[Project]
        """
        self.rows = self._define_list(rows, Project)
