# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .upload_metadata import UploadMetadata


@JsonMap({})
class VideoFetch(BaseModel):
    """VideoFetch

    :param metadata: The nested schema to upload a video.
    :type metadata: UploadMetadata
    :param url: url where the video to be fetched is located.
    :type url: str
    """

    def __init__(self, metadata: UploadMetadata, url: str):
        """VideoFetch

        :param metadata: The nested schema to upload a video.
        :type metadata: UploadMetadata
        :param url: url where the video to be fetched is located.
        :type url: str
        """
        self.metadata = self._define_object(metadata, UploadMetadata)
        self.url = self._define_str("url", url, min_length=1, max_length=2083)
