# This file was generated by liblab | https://liblab.com/

from enum import Enum


class VideoStatus(Enum):
    """An enumeration representing different categories.

    :cvar WAITINGFORUPLOAD: "waiting_for_upload"
    :vartype WAITINGFORUPLOAD: str
    :cvar READY: "ready"
    :vartype READY: str
    :cvar QUEUED: "queued"
    :vartype QUEUED: str
    :cvar COMPLETED: "completed"
    :vartype COMPLETED: str
    :cvar ERRORED: "errored"
    :vartype ERRORED: str
    """

    WAITINGFORUPLOAD = "waiting_for_upload"
    READY = "ready"
    QUEUED = "queued"
    COMPLETED = "completed"
    ERRORED = "errored"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, VideoStatus._member_map_.values()))
