# Generated by Django 4.2.7 on 2023-11-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_energiepartagee', '0067_discount_actor_villageoise'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='discount',
            field=models.ManyToManyField(blank=True, max_length=25, null=True, to='djangoldp_energiepartagee.discount', verbose_name='Réduction appliquée'),
        ),
    ]
