# Generated by Django 4.2.7 on 2023-11-28 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_energiepartagee', '0070_contribution_updatereminderdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedactor',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
    ]
