# Generated by Django 4.2.11 on 2024-09-19 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("djangoldp_energiepartagee", "0133_alter_actor_lat_alter_productionsite_lat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shareholder",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shareholders",
                to="djangoldp_energiepartagee.actor",
                verbose_name="Actionnaire",
            ),
        ),
        migrations.AlterField(
            model_name="shareholder",
            name="capital_distribution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shareholders",
                to="djangoldp_energiepartagee.capitaldistribution",
                verbose_name="Acteur",
            ),
        ),
    ]
