
# This file was generated by 'versioneer.py' (0.29+8.gf9bbd1b) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-27T16:14:42+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "16dbe46a343b592df0723e320a08f08be442592d",
 "version": "0.65.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
