# coding: utf-8

"""
    Orbit Determination API

    Orbit Determination API

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_determination_python_client.models.rotating_local_frame_id import RotatingLocalFrameId

class TestRotatingLocalFrameId(unittest.TestCase):
    """RotatingLocalFrameId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRotatingLocalFrameId(self):
        """Test RotatingLocalFrameId"""
        # inst = RotatingLocalFrameId()

if __name__ == '__main__':
    unittest.main()
