# coding: utf-8

"""
    Orbit Determination API

    Orbit Determination API

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_determination_python_client.models.least_squares_optimizer_type import LeastSquaresOptimizerType

class TestLeastSquaresOptimizerType(unittest.TestCase):
    """LeastSquaresOptimizerType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLeastSquaresOptimizerType(self):
        """Test LeastSquaresOptimizerType"""
        # inst = LeastSquaresOptimizerType()

if __name__ == '__main__':
    unittest.main()
