# coding: utf-8

"""
    Orbit Determination API

    Orbit Determination API

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_determination_python_client.models.dated_estimated_residuals import DatedEstimatedResiduals

class TestDatedEstimatedResiduals(unittest.TestCase):
    """DatedEstimatedResiduals unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatedEstimatedResiduals:
        """Test DatedEstimatedResiduals
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatedEstimatedResiduals`
        """
        model = DatedEstimatedResiduals()
        if include_optional:
            return DatedEstimatedResiduals(
                dates = [
                    datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
                    ],
                normalization_flag = True,
                rejection_status = [
                    True
                    ],
                description = [
                    spacetower_orbit_determination_python_client.models.field_description.FieldDescription(
                        index = 56, 
                        name = '', 
                        label = '', 
                        units = '', )
                    ]
            )
        else:
            return DatedEstimatedResiduals(
        )
        """

    def testDatedEstimatedResiduals(self):
        """Test DatedEstimatedResiduals"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
