# coding: utf-8

"""
    Orbit Determination API

    Orbit Determination API

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_determination_python_client.models.kalman_thrust_scale_factors_estimation_request import KalmanThrustScaleFactorsEstimationRequest

class TestKalmanThrustScaleFactorsEstimationRequest(unittest.TestCase):
    """KalmanThrustScaleFactorsEstimationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KalmanThrustScaleFactorsEstimationRequest:
        """Test KalmanThrustScaleFactorsEstimationRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KalmanThrustScaleFactorsEstimationRequest`
        """
        model = KalmanThrustScaleFactorsEstimationRequest()
        if include_optional:
            return KalmanThrustScaleFactorsEstimationRequest(
                scale_factor_x_initial_standard_deviation = 1.337,
                scale_factor_y_initial_standard_deviation = 1.337,
                scale_factor_z_initial_standard_deviation = 1.337,
                scale_factor_x_process_noise_standard_deviation = 1.337,
                scale_factor_y_process_noise_standard_deviation = 1.337,
                scale_factor_z_process_noise_standard_deviation = 1.337
            )
        else:
            return KalmanThrustScaleFactorsEstimationRequest(
                scale_factor_x_initial_standard_deviation = 1.337,
                scale_factor_y_initial_standard_deviation = 1.337,
                scale_factor_z_initial_standard_deviation = 1.337,
                scale_factor_x_process_noise_standard_deviation = 1.337,
                scale_factor_y_process_noise_standard_deviation = 1.337,
                scale_factor_z_process_noise_standard_deviation = 1.337,
        )
        """

    def testKalmanThrustScaleFactorsEstimationRequest(self):
        """Test KalmanThrustScaleFactorsEstimationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
