# coding: utf-8

"""
    Orbit Determination API

    Orbit Determination API

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_determination_python_client.models.perturbation_type import PerturbationType

class TestPerturbationType(unittest.TestCase):
    """PerturbationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPerturbationType(self):
        """Test PerturbationType"""
        # inst = PerturbationType()

if __name__ == '__main__':
    unittest.main()
