# coding: utf-8

"""
    Orbit Determination API

    Orbit Determination API

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_determination_python_client.models.isotropic_object_state_estimate import IsotropicObjectStateEstimate

class TestIsotropicObjectStateEstimate(unittest.TestCase):
    """IsotropicObjectStateEstimate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IsotropicObjectStateEstimate:
        """Test IsotropicObjectStateEstimate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IsotropicObjectStateEstimate`
        """
        model = IsotropicObjectStateEstimate()
        if include_optional:
            return IsotropicObjectStateEstimate(
                orbit = spacetower_orbit_determination_python_client.models.orbit.Orbit(
                    orbit_type = 'CARTESIAN', ),
                space_object = spacetower_orbit_determination_python_client.models.isotropic_object.IsotropicObject()
            )
        else:
            return IsotropicObjectStateEstimate(
                orbit = spacetower_orbit_determination_python_client.models.orbit.Orbit(
                    orbit_type = 'CARTESIAN', ),
        )
        """

    def testIsotropicObjectStateEstimate(self):
        """Test IsotropicObjectStateEstimate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
