# coding: utf-8

"""
    Orbit Determination API

    Orbit Determination API

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_determination_python_client.models.constant_noise_provider import ConstantNoiseProvider

class TestConstantNoiseProvider(unittest.TestCase):
    """ConstantNoiseProvider unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConstantNoiseProvider:
        """Test ConstantNoiseProvider
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConstantNoiseProvider`
        """
        model = ConstantNoiseProvider()
        if include_optional:
            return ConstantNoiseProvider(
                cartesian_standard_deviations = spacetower_orbit_determination_python_client.models.cartesian_process_noise_diagonal_matrix.CartesianProcessNoiseDiagonalMatrix(
                    frame_id = 'CIRF', 
                    position_x_coefficient = 0, 
                    position_y_coefficient = 0, 
                    position_z_coefficient = 0, 
                    velocity_x_coefficient = 0, 
                    velocity_y_coefficient = 0, 
                    velocity_z_coefficient = 0, )
            )
        else:
            return ConstantNoiseProvider(
        )
        """

    def testConstantNoiseProvider(self):
        """Test ConstantNoiseProvider"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
