# coding: utf-8

"""
    Orbit Determination API

    Orbit Determination API

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_determination_python_client.models.batch_residuals import BatchResiduals

class TestBatchResiduals(unittest.TestCase):
    """BatchResiduals unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchResiduals:
        """Test BatchResiduals
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchResiduals`
        """
        model = BatchResiduals()
        if include_optional:
            return BatchResiduals(
                dates = [
                    datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
                    ],
                normalization_flag = True,
                rejection_status = [
                    True
                    ],
                description = [
                    spacetower_orbit_determination_python_client.models.field_description.FieldDescription(
                        index = 56, 
                        name = '', 
                        label = '', 
                        units = '', )
                    ],
                residuals = spacetower_orbit_determination_python_client.models.residuals.Residuals(
                    residuals = [
                        [
                            1.337
                            ]
                        ], )
            )
        else:
            return BatchResiduals(
        )
        """

    def testBatchResiduals(self):
        """Test BatchResiduals"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
