# coding: utf-8

"""
    Orbit Determination API

    Orbit Determination API

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_determination_python_client.models.uncertainty_estimate import UncertaintyEstimate

class TestUncertaintyEstimate(unittest.TestCase):
    """UncertaintyEstimate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UncertaintyEstimate:
        """Test UncertaintyEstimate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UncertaintyEstimate`
        """
        model = UncertaintyEstimate()
        if include_optional:
            return UncertaintyEstimate(
                orbital_covariance_matrix = spacetower_orbit_determination_python_client.models.orbital_covariance_matrix.OrbitalCovarianceMatrix(
                    covariance_orbit_type = 'CARTESIAN', ),
                drag_coefficient_standard_deviation = 1.337,
                reflectivity_coefficient_standard_deviation = 1.337,
                thrust_parameters_standard_deviation = [
                    1.337
                    ],
                satellite_clock_offset_standard_deviation = 1.337
            )
        else:
            return UncertaintyEstimate(
        )
        """

    def testUncertaintyEstimate(self):
        """Test UncertaintyEstimate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
