# coding: utf-8

"""
    Orbit Determination API

    Orbit Determination API

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_determination_python_client.models.kalman_drag_coefficient_estimation_request import KalmanDragCoefficientEstimationRequest

class TestKalmanDragCoefficientEstimationRequest(unittest.TestCase):
    """KalmanDragCoefficientEstimationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KalmanDragCoefficientEstimationRequest:
        """Test KalmanDragCoefficientEstimationRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KalmanDragCoefficientEstimationRequest`
        """
        model = KalmanDragCoefficientEstimationRequest()
        if include_optional:
            return KalmanDragCoefficientEstimationRequest(
                standard_deviation = 0,
                process_noise_standard_deviation = 0
            )
        else:
            return KalmanDragCoefficientEstimationRequest(
                standard_deviation = 0,
        )
        """

    def testKalmanDragCoefficientEstimationRequest(self):
        """Test KalmanDragCoefficientEstimationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
