# This file was generated by Nuitka

# Stubs included by default
from fastapi import File, UploadFile
from uuid import uuid4
from datetime import datetime
from tools.database import lite_client

def set_script_name(data: dict) -> typing.Any:
    ...
def delete_script(data: dict) -> typing.Any:
    ...
def set_main_script(data: dict) -> typing.Any:
    ...
def update_script(data: dict) -> typing.Any:
    ...

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import fastapi
import fastapi.File
import fastapi.UploadFile
import tools
import tools.database
import uuid
import datetime