# coding: utf-8

"""
    Infrahub-API

    Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperstack.models.admincreditpostpayload import Admincreditpostpayload

class TestAdmincreditpostpayload(unittest.TestCase):
    """Admincreditpostpayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Admincreditpostpayload:
        """Test Admincreditpostpayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Admincreditpostpayload`
        """
        model = Admincreditpostpayload()
        if include_optional:
            return Admincreditpostpayload(
                credit = 0,
                reason = ''
            )
        else:
            return Admincreditpostpayload(
                credit = 0,
                reason = '',
        )
        """

    def testAdmincreditpostpayload(self):
        """Test Admincreditpostpayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
