"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from orq_poc_python_multi_env_version.types import BaseModel
from orq_poc_python_multi_env_version.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class DuplicatePromptRequestTypedDict(TypedDict):
    id: str
    r"""Prompt ID"""


class DuplicatePromptRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Prompt ID"""
