
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-26T17:31:58-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "f9e53f418e5131bcb7ca640672c24b994c815a69",
 "version": "1.1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
