
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-26T15:51:00+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b06ef99abd4eeef2471d0e2757e556582df7d187",
 "version": "0.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
