# sleep
SLEEP_TIME = 1
LONG_SLEEP_TIME = 2
MONITOR_TIME = 150
# ENV VARIABLES
PROPHECY_PAT = "PROPHECY_PAT"

PROPHECY_URL = "PROPHECY_URL"

PROJECT_ID = "PROJECT_ID"
PIPELINE_ID = "PIPELINE_ID"
SEND_EMAIL = "SEND_EMAIL"
BRANCH = "BRANCH"

# EXCEL COLUMN NAMES
CATALOG_COL = "Target Catalog"
DB_COL = "Target Database"
TABLE_COL = "Target Table"
COLNAME_COL = "Column Name"
UPSTREAM_TRANSFORMATION_COL = "Upstream Lineage"
