
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-27T19:07:43+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ddece52141307ce601fd417e438b4250828712c3",
 "version": "1.8.86"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
