
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-26T12:45:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b3faad5456cd9586e9237554e5c7850d9f201f3",
 "version": "1.31.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
