# Generated by Django 5.1.3 on 2024-11-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='expression',
            field=models.CharField(default=1, max_length=128, verbose_name='Expression'),
            preserve_default=False,
        ),
    ]
