
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-27T09:56:51-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "65b27a98384d0a9457e2ea956b102708ac79c69b",
 "version": "3.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
